// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// S3backendsColumns holds the columns for the "s3backends" table.
	S3backendsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "endpoint", Type: field.TypeString, Nullable: true},
		{Name: "region", Type: field.TypeString, Default: "us-east-1"},
		{Name: "bucket", Type: field.TypeString},
		{Name: "access_key", Type: field.TypeString},
		{Name: "secret_key", Type: field.TypeString},
		{Name: "session_token", Type: field.TypeString, Nullable: true},
		{Name: "path_style", Type: field.TypeBool, Default: false},
		{Name: "key_prefix", Type: field.TypeString, Nullable: true},
		{Name: "mount_path", Type: field.TypeString, Unique: true},
		{Name: "is_enabled", Type: field.TypeBool, Default: true},
		{Name: "is_readonly", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// S3backendsTable holds the schema information for the "s3backends" table.
	S3backendsTable = &schema.Table{
		Name:       "s3backends",
		Columns:    S3backendsColumns,
		PrimaryKey: []*schema.Column{S3backendsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "user"}, Default: "user"},
		{Name: "is_enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// S3backendUsersColumns holds the columns for the "s3backend_users" table.
	S3backendUsersColumns = []*schema.Column{
		{Name: "s3backend_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// S3backendUsersTable holds the schema information for the "s3backend_users" table.
	S3backendUsersTable = &schema.Table{
		Name:       "s3backend_users",
		Columns:    S3backendUsersColumns,
		PrimaryKey: []*schema.Column{S3backendUsersColumns[0], S3backendUsersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "s3backend_users_s3backend_id",
				Columns:    []*schema.Column{S3backendUsersColumns[0]},
				RefColumns: []*schema.Column{S3backendsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "s3backend_users_user_id",
				Columns:    []*schema.Column{S3backendUsersColumns[1]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		S3backendsTable,
		UsersTable,
		S3backendUsersTable,
	}
)

func init() {
	S3backendUsersTable.ForeignKeys[0].RefTable = S3backendsTable
	S3backendUsersTable.ForeignKeys[1].RefTable = UsersTable
}
