// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/example/webdav-s3/ent/s3backend"
	"github.com/example/webdav-s3/ent/schema"
	"github.com/example/webdav-s3/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	s3backendFields := schema.S3Backend{}.Fields()
	_ = s3backendFields
	// s3backendDescName is the schema descriptor for name field.
	s3backendDescName := s3backendFields[0].Descriptor()
	// s3backend.NameValidator is a validator for the "name" field. It is called by the builders before save.
	s3backend.NameValidator = s3backendDescName.Validators[0].(func(string) error)
	// s3backendDescRegion is the schema descriptor for region field.
	s3backendDescRegion := s3backendFields[2].Descriptor()
	// s3backend.DefaultRegion holds the default value on creation for the region field.
	s3backend.DefaultRegion = s3backendDescRegion.Default.(string)
	// s3backendDescBucket is the schema descriptor for bucket field.
	s3backendDescBucket := s3backendFields[3].Descriptor()
	// s3backend.BucketValidator is a validator for the "bucket" field. It is called by the builders before save.
	s3backend.BucketValidator = s3backendDescBucket.Validators[0].(func(string) error)
	// s3backendDescAccessKey is the schema descriptor for access_key field.
	s3backendDescAccessKey := s3backendFields[4].Descriptor()
	// s3backend.AccessKeyValidator is a validator for the "access_key" field. It is called by the builders before save.
	s3backend.AccessKeyValidator = s3backendDescAccessKey.Validators[0].(func(string) error)
	// s3backendDescSecretKey is the schema descriptor for secret_key field.
	s3backendDescSecretKey := s3backendFields[5].Descriptor()
	// s3backend.SecretKeyValidator is a validator for the "secret_key" field. It is called by the builders before save.
	s3backend.SecretKeyValidator = s3backendDescSecretKey.Validators[0].(func(string) error)
	// s3backendDescPathStyle is the schema descriptor for path_style field.
	s3backendDescPathStyle := s3backendFields[7].Descriptor()
	// s3backend.DefaultPathStyle holds the default value on creation for the path_style field.
	s3backend.DefaultPathStyle = s3backendDescPathStyle.Default.(bool)
	// s3backendDescMountPath is the schema descriptor for mount_path field.
	s3backendDescMountPath := s3backendFields[9].Descriptor()
	// s3backend.MountPathValidator is a validator for the "mount_path" field. It is called by the builders before save.
	s3backend.MountPathValidator = s3backendDescMountPath.Validators[0].(func(string) error)
	// s3backendDescIsEnabled is the schema descriptor for is_enabled field.
	s3backendDescIsEnabled := s3backendFields[10].Descriptor()
	// s3backend.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	s3backend.DefaultIsEnabled = s3backendDescIsEnabled.Default.(bool)
	// s3backendDescIsReadonly is the schema descriptor for is_readonly field.
	s3backendDescIsReadonly := s3backendFields[11].Descriptor()
	// s3backend.DefaultIsReadonly holds the default value on creation for the is_readonly field.
	s3backend.DefaultIsReadonly = s3backendDescIsReadonly.Default.(bool)
	// s3backendDescCreatedAt is the schema descriptor for created_at field.
	s3backendDescCreatedAt := s3backendFields[12].Descriptor()
	// s3backend.DefaultCreatedAt holds the default value on creation for the created_at field.
	s3backend.DefaultCreatedAt = s3backendDescCreatedAt.Default.(func() time.Time)
	// s3backendDescUpdatedAt is the schema descriptor for updated_at field.
	s3backendDescUpdatedAt := s3backendFields[13].Descriptor()
	// s3backend.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	s3backend.DefaultUpdatedAt = s3backendDescUpdatedAt.Default.(func() time.Time)
	// s3backend.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	s3backend.UpdateDefaultUpdatedAt = s3backendDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescIsEnabled is the schema descriptor for is_enabled field.
	userDescIsEnabled := userFields[3].Descriptor()
	// user.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	user.DefaultIsEnabled = userDescIsEnabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
