// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/webdav-s3/ent/predicate"
	"github.com/example/webdav-s3/ent/s3backend"
	"github.com/example/webdav-s3/ent/user"
)

// S3BackendUpdate is the builder for updating S3Backend entities.
type S3BackendUpdate struct {
	config
	hooks    []Hook
	mutation *S3BackendMutation
}

// Where appends a list predicates to the S3BackendUpdate builder.
func (_u *S3BackendUpdate) Where(ps ...predicate.S3Backend) *S3BackendUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *S3BackendUpdate) SetName(v string) *S3BackendUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableName(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *S3BackendUpdate) SetEndpoint(v string) *S3BackendUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableEndpoint(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *S3BackendUpdate) ClearEndpoint() *S3BackendUpdate {
	_u.mutation.ClearEndpoint()
	return _u
}

// SetRegion sets the "region" field.
func (_u *S3BackendUpdate) SetRegion(v string) *S3BackendUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableRegion(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *S3BackendUpdate) SetBucket(v string) *S3BackendUpdate {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableBucket(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetAccessKey sets the "access_key" field.
func (_u *S3BackendUpdate) SetAccessKey(v string) *S3BackendUpdate {
	_u.mutation.SetAccessKey(v)
	return _u
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableAccessKey(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetAccessKey(*v)
	}
	return _u
}

// SetSecretKey sets the "secret_key" field.
func (_u *S3BackendUpdate) SetSecretKey(v string) *S3BackendUpdate {
	_u.mutation.SetSecretKey(v)
	return _u
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableSecretKey(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetSecretKey(*v)
	}
	return _u
}

// SetSessionToken sets the "session_token" field.
func (_u *S3BackendUpdate) SetSessionToken(v string) *S3BackendUpdate {
	_u.mutation.SetSessionToken(v)
	return _u
}

// SetNillableSessionToken sets the "session_token" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableSessionToken(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetSessionToken(*v)
	}
	return _u
}

// ClearSessionToken clears the value of the "session_token" field.
func (_u *S3BackendUpdate) ClearSessionToken() *S3BackendUpdate {
	_u.mutation.ClearSessionToken()
	return _u
}

// SetPathStyle sets the "path_style" field.
func (_u *S3BackendUpdate) SetPathStyle(v bool) *S3BackendUpdate {
	_u.mutation.SetPathStyle(v)
	return _u
}

// SetNillablePathStyle sets the "path_style" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillablePathStyle(v *bool) *S3BackendUpdate {
	if v != nil {
		_u.SetPathStyle(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *S3BackendUpdate) SetKeyPrefix(v string) *S3BackendUpdate {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableKeyPrefix(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// ClearKeyPrefix clears the value of the "key_prefix" field.
func (_u *S3BackendUpdate) ClearKeyPrefix() *S3BackendUpdate {
	_u.mutation.ClearKeyPrefix()
	return _u
}

// SetMountPath sets the "mount_path" field.
func (_u *S3BackendUpdate) SetMountPath(v string) *S3BackendUpdate {
	_u.mutation.SetMountPath(v)
	return _u
}

// SetNillableMountPath sets the "mount_path" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableMountPath(v *string) *S3BackendUpdate {
	if v != nil {
		_u.SetMountPath(*v)
	}
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *S3BackendUpdate) SetIsPrimary(v bool) *S3BackendUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableIsPrimary(v *bool) *S3BackendUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *S3BackendUpdate) SetIsEnabled(v bool) *S3BackendUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableIsEnabled(v *bool) *S3BackendUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetIsReadonly sets the "is_readonly" field.
func (_u *S3BackendUpdate) SetIsReadonly(v bool) *S3BackendUpdate {
	_u.mutation.SetIsReadonly(v)
	return _u
}

// SetNillableIsReadonly sets the "is_readonly" field if the given value is not nil.
func (_u *S3BackendUpdate) SetNillableIsReadonly(v *bool) *S3BackendUpdate {
	if v != nil {
		_u.SetIsReadonly(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *S3BackendUpdate) SetUpdatedAt(v time.Time) *S3BackendUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *S3BackendUpdate) AddUserIDs(ids ...int) *S3BackendUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *S3BackendUpdate) AddUsers(v ...*User) *S3BackendUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the S3BackendMutation object of the builder.
func (_u *S3BackendUpdate) Mutation() *S3BackendMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *S3BackendUpdate) ClearUsers() *S3BackendUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *S3BackendUpdate) RemoveUserIDs(ids ...int) *S3BackendUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *S3BackendUpdate) RemoveUsers(v ...*User) *S3BackendUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *S3BackendUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *S3BackendUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *S3BackendUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *S3BackendUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *S3BackendUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := s3backend.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *S3BackendUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := s3backend.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "S3Backend.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := s3backend.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "S3Backend.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessKey(); ok {
		if err := s3backend.AccessKeyValidator(v); err != nil {
			return &ValidationError{Name: "access_key", err: fmt.Errorf(`ent: validator failed for field "S3Backend.access_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretKey(); ok {
		if err := s3backend.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "S3Backend.secret_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MountPath(); ok {
		if err := s3backend.MountPathValidator(v); err != nil {
			return &ValidationError{Name: "mount_path", err: fmt.Errorf(`ent: validator failed for field "S3Backend.mount_path": %w`, err)}
		}
	}
	return nil
}

func (_u *S3BackendUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3backend.Table, s3backend.Columns, sqlgraph.NewFieldSpec(s3backend.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(s3backend.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(s3backend.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(s3backend.FieldEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(s3backend.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(s3backend.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKey(); ok {
		_spec.SetField(s3backend.FieldAccessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKey(); ok {
		_spec.SetField(s3backend.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionToken(); ok {
		_spec.SetField(s3backend.FieldSessionToken, field.TypeString, value)
	}
	if _u.mutation.SessionTokenCleared() {
		_spec.ClearField(s3backend.FieldSessionToken, field.TypeString)
	}
	if value, ok := _u.mutation.PathStyle(); ok {
		_spec.SetField(s3backend.FieldPathStyle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(s3backend.FieldKeyPrefix, field.TypeString, value)
	}
	if _u.mutation.KeyPrefixCleared() {
		_spec.ClearField(s3backend.FieldKeyPrefix, field.TypeString)
	}
	if value, ok := _u.mutation.MountPath(); ok {
		_spec.SetField(s3backend.FieldMountPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(s3backend.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(s3backend.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsReadonly(); ok {
		_spec.SetField(s3backend.FieldIsReadonly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(s3backend.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   s3backend.UsersTable,
			Columns: s3backend.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   s3backend.UsersTable,
			Columns: s3backend.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   s3backend.UsersTable,
			Columns: s3backend.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3backend.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// S3BackendUpdateOne is the builder for updating a single S3Backend entity.
type S3BackendUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *S3BackendMutation
}

// SetName sets the "name" field.
func (_u *S3BackendUpdateOne) SetName(v string) *S3BackendUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableName(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *S3BackendUpdateOne) SetEndpoint(v string) *S3BackendUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableEndpoint(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *S3BackendUpdateOne) ClearEndpoint() *S3BackendUpdateOne {
	_u.mutation.ClearEndpoint()
	return _u
}

// SetRegion sets the "region" field.
func (_u *S3BackendUpdateOne) SetRegion(v string) *S3BackendUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableRegion(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *S3BackendUpdateOne) SetBucket(v string) *S3BackendUpdateOne {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableBucket(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetAccessKey sets the "access_key" field.
func (_u *S3BackendUpdateOne) SetAccessKey(v string) *S3BackendUpdateOne {
	_u.mutation.SetAccessKey(v)
	return _u
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableAccessKey(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetAccessKey(*v)
	}
	return _u
}

// SetSecretKey sets the "secret_key" field.
func (_u *S3BackendUpdateOne) SetSecretKey(v string) *S3BackendUpdateOne {
	_u.mutation.SetSecretKey(v)
	return _u
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableSecretKey(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetSecretKey(*v)
	}
	return _u
}

// SetSessionToken sets the "session_token" field.
func (_u *S3BackendUpdateOne) SetSessionToken(v string) *S3BackendUpdateOne {
	_u.mutation.SetSessionToken(v)
	return _u
}

// SetNillableSessionToken sets the "session_token" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableSessionToken(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetSessionToken(*v)
	}
	return _u
}

// ClearSessionToken clears the value of the "session_token" field.
func (_u *S3BackendUpdateOne) ClearSessionToken() *S3BackendUpdateOne {
	_u.mutation.ClearSessionToken()
	return _u
}

// SetPathStyle sets the "path_style" field.
func (_u *S3BackendUpdateOne) SetPathStyle(v bool) *S3BackendUpdateOne {
	_u.mutation.SetPathStyle(v)
	return _u
}

// SetNillablePathStyle sets the "path_style" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillablePathStyle(v *bool) *S3BackendUpdateOne {
	if v != nil {
		_u.SetPathStyle(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *S3BackendUpdateOne) SetKeyPrefix(v string) *S3BackendUpdateOne {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableKeyPrefix(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// ClearKeyPrefix clears the value of the "key_prefix" field.
func (_u *S3BackendUpdateOne) ClearKeyPrefix() *S3BackendUpdateOne {
	_u.mutation.ClearKeyPrefix()
	return _u
}

// SetMountPath sets the "mount_path" field.
func (_u *S3BackendUpdateOne) SetMountPath(v string) *S3BackendUpdateOne {
	_u.mutation.SetMountPath(v)
	return _u
}

// SetNillableMountPath sets the "mount_path" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableMountPath(v *string) *S3BackendUpdateOne {
	if v != nil {
		_u.SetMountPath(*v)
	}
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *S3BackendUpdateOne) SetIsPrimary(v bool) *S3BackendUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableIsPrimary(v *bool) *S3BackendUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *S3BackendUpdateOne) SetIsEnabled(v bool) *S3BackendUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableIsEnabled(v *bool) *S3BackendUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetIsReadonly sets the "is_readonly" field.
func (_u *S3BackendUpdateOne) SetIsReadonly(v bool) *S3BackendUpdateOne {
	_u.mutation.SetIsReadonly(v)
	return _u
}

// SetNillableIsReadonly sets the "is_readonly" field if the given value is not nil.
func (_u *S3BackendUpdateOne) SetNillableIsReadonly(v *bool) *S3BackendUpdateOne {
	if v != nil {
		_u.SetIsReadonly(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *S3BackendUpdateOne) SetUpdatedAt(v time.Time) *S3BackendUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *S3BackendUpdateOne) AddUserIDs(ids ...int) *S3BackendUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *S3BackendUpdateOne) AddUsers(v ...*User) *S3BackendUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the S3BackendMutation object of the builder.
func (_u *S3BackendUpdateOne) Mutation() *S3BackendMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *S3BackendUpdateOne) ClearUsers() *S3BackendUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *S3BackendUpdateOne) RemoveUserIDs(ids ...int) *S3BackendUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *S3BackendUpdateOne) RemoveUsers(v ...*User) *S3BackendUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the S3BackendUpdate builder.
func (_u *S3BackendUpdateOne) Where(ps ...predicate.S3Backend) *S3BackendUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *S3BackendUpdateOne) Select(field string, fields ...string) *S3BackendUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated S3Backend entity.
func (_u *S3BackendUpdateOne) Save(ctx context.Context) (*S3Backend, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *S3BackendUpdateOne) SaveX(ctx context.Context) *S3Backend {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *S3BackendUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *S3BackendUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *S3BackendUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := s3backend.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *S3BackendUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := s3backend.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "S3Backend.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Bucket(); ok {
		if err := s3backend.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "S3Backend.bucket": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessKey(); ok {
		if err := s3backend.AccessKeyValidator(v); err != nil {
			return &ValidationError{Name: "access_key", err: fmt.Errorf(`ent: validator failed for field "S3Backend.access_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretKey(); ok {
		if err := s3backend.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "S3Backend.secret_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MountPath(); ok {
		if err := s3backend.MountPathValidator(v); err != nil {
			return &ValidationError{Name: "mount_path", err: fmt.Errorf(`ent: validator failed for field "S3Backend.mount_path": %w`, err)}
		}
	}
	return nil
}

func (_u *S3BackendUpdateOne) sqlSave(ctx context.Context) (_node *S3Backend, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(s3backend.Table, s3backend.Columns, sqlgraph.NewFieldSpec(s3backend.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "S3Backend.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, s3backend.FieldID)
		for _, f := range fields {
			if !s3backend.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != s3backend.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(s3backend.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(s3backend.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(s3backend.FieldEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(s3backend.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(s3backend.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKey(); ok {
		_spec.SetField(s3backend.FieldAccessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKey(); ok {
		_spec.SetField(s3backend.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionToken(); ok {
		_spec.SetField(s3backend.FieldSessionToken, field.TypeString, value)
	}
	if _u.mutation.SessionTokenCleared() {
		_spec.ClearField(s3backend.FieldSessionToken, field.TypeString)
	}
	if value, ok := _u.mutation.PathStyle(); ok {
		_spec.SetField(s3backend.FieldPathStyle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(s3backend.FieldKeyPrefix, field.TypeString, value)
	}
	if _u.mutation.KeyPrefixCleared() {
		_spec.ClearField(s3backend.FieldKeyPrefix, field.TypeString)
	}
	if value, ok := _u.mutation.MountPath(); ok {
		_spec.SetField(s3backend.FieldMountPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(s3backend.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(s3backend.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsReadonly(); ok {
		_spec.SetField(s3backend.FieldIsReadonly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(s3backend.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   s3backend.UsersTable,
			Columns: s3backend.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   s3backend.UsersTable,
			Columns: s3backend.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   s3backend.UsersTable,
			Columns: s3backend.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &S3Backend{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{s3backend.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
