// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/example/webdav-s3/ent/s3backend"
)

// S3Backend is the model entity for the S3Backend schema.
type S3Backend struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Human-readable backend identifier
	Name string `json:"name,omitempty"`
	// S3 API endpoint URL (empty for AWS)
	Endpoint string `json:"endpoint,omitempty"`
	// AWS region
	Region string `json:"region,omitempty"`
	// S3 bucket name
	Bucket string `json:"bucket,omitempty"`
	// AWS access key ID
	AccessKey string `json:"-"`
	// AWS secret access key
	SecretKey string `json:"-"`
	// AWS session token (temporary credentials)
	SessionToken string `json:"-"`
	// Use path-style URLs (required for MinIO/R2)
	PathStyle bool `json:"path_style,omitempty"`
	// Optional prefix for all keys in this backend
	KeyPrefix string `json:"key_prefix,omitempty"`
	// Virtual path to mount (e.g., /backup). Multiple backends with same path = replication
	MountPath string `json:"mount_path,omitempty"`
	// Primary backend for reading when multiple backends share same mount_path
	IsPrimary bool `json:"is_primary,omitempty"`
	// Whether this backend is active
	IsEnabled bool `json:"is_enabled,omitempty"`
	// Whether this backend is read-only
	IsReadonly bool `json:"is_readonly,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the S3BackendQuery when eager-loading is set.
	Edges        S3BackendEdges `json:"edges"`
	selectValues sql.SelectValues
}

// S3BackendEdges holds the relations/edges for other nodes in the graph.
type S3BackendEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e S3BackendEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*S3Backend) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case s3backend.FieldPathStyle, s3backend.FieldIsPrimary, s3backend.FieldIsEnabled, s3backend.FieldIsReadonly:
			values[i] = new(sql.NullBool)
		case s3backend.FieldID:
			values[i] = new(sql.NullInt64)
		case s3backend.FieldName, s3backend.FieldEndpoint, s3backend.FieldRegion, s3backend.FieldBucket, s3backend.FieldAccessKey, s3backend.FieldSecretKey, s3backend.FieldSessionToken, s3backend.FieldKeyPrefix, s3backend.FieldMountPath:
			values[i] = new(sql.NullString)
		case s3backend.FieldCreatedAt, s3backend.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the S3Backend fields.
func (_m *S3Backend) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case s3backend.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case s3backend.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case s3backend.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case s3backend.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case s3backend.FieldBucket:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket", values[i])
			} else if value.Valid {
				_m.Bucket = value.String
			}
		case s3backend.FieldAccessKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_key", values[i])
			} else if value.Valid {
				_m.AccessKey = value.String
			}
		case s3backend.FieldSecretKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_key", values[i])
			} else if value.Valid {
				_m.SecretKey = value.String
			}
		case s3backend.FieldSessionToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_token", values[i])
			} else if value.Valid {
				_m.SessionToken = value.String
			}
		case s3backend.FieldPathStyle:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field path_style", values[i])
			} else if value.Valid {
				_m.PathStyle = value.Bool
			}
		case s3backend.FieldKeyPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_prefix", values[i])
			} else if value.Valid {
				_m.KeyPrefix = value.String
			}
		case s3backend.FieldMountPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mount_path", values[i])
			} else if value.Valid {
				_m.MountPath = value.String
			}
		case s3backend.FieldIsPrimary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_primary", values[i])
			} else if value.Valid {
				_m.IsPrimary = value.Bool
			}
		case s3backend.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = value.Bool
			}
		case s3backend.FieldIsReadonly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_readonly", values[i])
			} else if value.Valid {
				_m.IsReadonly = value.Bool
			}
		case s3backend.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case s3backend.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the S3Backend.
// This includes values selected through modifiers, order, etc.
func (_m *S3Backend) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the S3Backend entity.
func (_m *S3Backend) QueryUsers() *UserQuery {
	return NewS3BackendClient(_m.config).QueryUsers(_m)
}

// Update returns a builder for updating this S3Backend.
// Note that you need to call S3Backend.Unwrap() before calling this method if this S3Backend
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *S3Backend) Update() *S3BackendUpdateOne {
	return NewS3BackendClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the S3Backend entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *S3Backend) Unwrap() *S3Backend {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: S3Backend is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *S3Backend) String() string {
	var builder strings.Builder
	builder.WriteString("S3Backend(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("bucket=")
	builder.WriteString(_m.Bucket)
	builder.WriteString(", ")
	builder.WriteString("access_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("secret_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("session_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("path_style=")
	builder.WriteString(fmt.Sprintf("%v", _m.PathStyle))
	builder.WriteString(", ")
	builder.WriteString("key_prefix=")
	builder.WriteString(_m.KeyPrefix)
	builder.WriteString(", ")
	builder.WriteString("mount_path=")
	builder.WriteString(_m.MountPath)
	builder.WriteString(", ")
	builder.WriteString("is_primary=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPrimary))
	builder.WriteString(", ")
	builder.WriteString("is_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEnabled))
	builder.WriteString(", ")
	builder.WriteString("is_readonly=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsReadonly))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// S3Backends is a parsable slice of S3Backend.
type S3Backends []*S3Backend
