// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/webdav-s3/ent/predicate"
	"github.com/example/webdav-s3/ent/s3backend"
)

// S3BackendDelete is the builder for deleting a S3Backend entity.
type S3BackendDelete struct {
	config
	hooks    []Hook
	mutation *S3BackendMutation
}

// Where appends a list predicates to the S3BackendDelete builder.
func (_d *S3BackendDelete) Where(ps ...predicate.S3Backend) *S3BackendDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *S3BackendDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *S3BackendDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *S3BackendDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(s3backend.Table, sqlgraph.NewFieldSpec(s3backend.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// S3BackendDeleteOne is the builder for deleting a single S3Backend entity.
type S3BackendDeleteOne struct {
	_d *S3BackendDelete
}

// Where appends a list predicates to the S3BackendDelete builder.
func (_d *S3BackendDeleteOne) Where(ps ...predicate.S3Backend) *S3BackendDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *S3BackendDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{s3backend.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *S3BackendDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
