// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/webdav-s3/ent/s3backend"
	"github.com/example/webdav-s3/ent/user"
)

// S3BackendCreate is the builder for creating a S3Backend entity.
type S3BackendCreate struct {
	config
	mutation *S3BackendMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *S3BackendCreate) SetName(v string) *S3BackendCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEndpoint sets the "endpoint" field.
func (_c *S3BackendCreate) SetEndpoint(v string) *S3BackendCreate {
	_c.mutation.SetEndpoint(v)
	return _c
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillableEndpoint(v *string) *S3BackendCreate {
	if v != nil {
		_c.SetEndpoint(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *S3BackendCreate) SetRegion(v string) *S3BackendCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillableRegion(v *string) *S3BackendCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *S3BackendCreate) SetBucket(v string) *S3BackendCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetAccessKey sets the "access_key" field.
func (_c *S3BackendCreate) SetAccessKey(v string) *S3BackendCreate {
	_c.mutation.SetAccessKey(v)
	return _c
}

// SetSecretKey sets the "secret_key" field.
func (_c *S3BackendCreate) SetSecretKey(v string) *S3BackendCreate {
	_c.mutation.SetSecretKey(v)
	return _c
}

// SetSessionToken sets the "session_token" field.
func (_c *S3BackendCreate) SetSessionToken(v string) *S3BackendCreate {
	_c.mutation.SetSessionToken(v)
	return _c
}

// SetNillableSessionToken sets the "session_token" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillableSessionToken(v *string) *S3BackendCreate {
	if v != nil {
		_c.SetSessionToken(*v)
	}
	return _c
}

// SetPathStyle sets the "path_style" field.
func (_c *S3BackendCreate) SetPathStyle(v bool) *S3BackendCreate {
	_c.mutation.SetPathStyle(v)
	return _c
}

// SetNillablePathStyle sets the "path_style" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillablePathStyle(v *bool) *S3BackendCreate {
	if v != nil {
		_c.SetPathStyle(*v)
	}
	return _c
}

// SetKeyPrefix sets the "key_prefix" field.
func (_c *S3BackendCreate) SetKeyPrefix(v string) *S3BackendCreate {
	_c.mutation.SetKeyPrefix(v)
	return _c
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillableKeyPrefix(v *string) *S3BackendCreate {
	if v != nil {
		_c.SetKeyPrefix(*v)
	}
	return _c
}

// SetMountPath sets the "mount_path" field.
func (_c *S3BackendCreate) SetMountPath(v string) *S3BackendCreate {
	_c.mutation.SetMountPath(v)
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *S3BackendCreate) SetIsEnabled(v bool) *S3BackendCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillableIsEnabled(v *bool) *S3BackendCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetIsReadonly sets the "is_readonly" field.
func (_c *S3BackendCreate) SetIsReadonly(v bool) *S3BackendCreate {
	_c.mutation.SetIsReadonly(v)
	return _c
}

// SetNillableIsReadonly sets the "is_readonly" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillableIsReadonly(v *bool) *S3BackendCreate {
	if v != nil {
		_c.SetIsReadonly(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *S3BackendCreate) SetCreatedAt(v time.Time) *S3BackendCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillableCreatedAt(v *time.Time) *S3BackendCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *S3BackendCreate) SetUpdatedAt(v time.Time) *S3BackendCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *S3BackendCreate) SetNillableUpdatedAt(v *time.Time) *S3BackendCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *S3BackendCreate) AddUserIDs(ids ...int) *S3BackendCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *S3BackendCreate) AddUsers(v ...*User) *S3BackendCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// Mutation returns the S3BackendMutation object of the builder.
func (_c *S3BackendCreate) Mutation() *S3BackendMutation {
	return _c.mutation
}

// Save creates the S3Backend in the database.
func (_c *S3BackendCreate) Save(ctx context.Context) (*S3Backend, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *S3BackendCreate) SaveX(ctx context.Context) *S3Backend {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *S3BackendCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *S3BackendCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *S3BackendCreate) defaults() {
	if _, ok := _c.mutation.Region(); !ok {
		v := s3backend.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.PathStyle(); !ok {
		v := s3backend.DefaultPathStyle
		_c.mutation.SetPathStyle(v)
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := s3backend.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.IsReadonly(); !ok {
		v := s3backend.DefaultIsReadonly
		_c.mutation.SetIsReadonly(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := s3backend.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := s3backend.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *S3BackendCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "S3Backend.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := s3backend.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "S3Backend.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "S3Backend.region"`)}
	}
	if _, ok := _c.mutation.Bucket(); !ok {
		return &ValidationError{Name: "bucket", err: errors.New(`ent: missing required field "S3Backend.bucket"`)}
	}
	if v, ok := _c.mutation.Bucket(); ok {
		if err := s3backend.BucketValidator(v); err != nil {
			return &ValidationError{Name: "bucket", err: fmt.Errorf(`ent: validator failed for field "S3Backend.bucket": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccessKey(); !ok {
		return &ValidationError{Name: "access_key", err: errors.New(`ent: missing required field "S3Backend.access_key"`)}
	}
	if v, ok := _c.mutation.AccessKey(); ok {
		if err := s3backend.AccessKeyValidator(v); err != nil {
			return &ValidationError{Name: "access_key", err: fmt.Errorf(`ent: validator failed for field "S3Backend.access_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretKey(); !ok {
		return &ValidationError{Name: "secret_key", err: errors.New(`ent: missing required field "S3Backend.secret_key"`)}
	}
	if v, ok := _c.mutation.SecretKey(); ok {
		if err := s3backend.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "S3Backend.secret_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PathStyle(); !ok {
		return &ValidationError{Name: "path_style", err: errors.New(`ent: missing required field "S3Backend.path_style"`)}
	}
	if _, ok := _c.mutation.MountPath(); !ok {
		return &ValidationError{Name: "mount_path", err: errors.New(`ent: missing required field "S3Backend.mount_path"`)}
	}
	if v, ok := _c.mutation.MountPath(); ok {
		if err := s3backend.MountPathValidator(v); err != nil {
			return &ValidationError{Name: "mount_path", err: fmt.Errorf(`ent: validator failed for field "S3Backend.mount_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		return &ValidationError{Name: "is_enabled", err: errors.New(`ent: missing required field "S3Backend.is_enabled"`)}
	}
	if _, ok := _c.mutation.IsReadonly(); !ok {
		return &ValidationError{Name: "is_readonly", err: errors.New(`ent: missing required field "S3Backend.is_readonly"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "S3Backend.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "S3Backend.updated_at"`)}
	}
	return nil
}

func (_c *S3BackendCreate) sqlSave(ctx context.Context) (*S3Backend, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *S3BackendCreate) createSpec() (*S3Backend, *sqlgraph.CreateSpec) {
	var (
		_node = &S3Backend{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(s3backend.Table, sqlgraph.NewFieldSpec(s3backend.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(s3backend.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Endpoint(); ok {
		_spec.SetField(s3backend.FieldEndpoint, field.TypeString, value)
		_node.Endpoint = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(s3backend.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(s3backend.FieldBucket, field.TypeString, value)
		_node.Bucket = value
	}
	if value, ok := _c.mutation.AccessKey(); ok {
		_spec.SetField(s3backend.FieldAccessKey, field.TypeString, value)
		_node.AccessKey = value
	}
	if value, ok := _c.mutation.SecretKey(); ok {
		_spec.SetField(s3backend.FieldSecretKey, field.TypeString, value)
		_node.SecretKey = value
	}
	if value, ok := _c.mutation.SessionToken(); ok {
		_spec.SetField(s3backend.FieldSessionToken, field.TypeString, value)
		_node.SessionToken = value
	}
	if value, ok := _c.mutation.PathStyle(); ok {
		_spec.SetField(s3backend.FieldPathStyle, field.TypeBool, value)
		_node.PathStyle = value
	}
	if value, ok := _c.mutation.KeyPrefix(); ok {
		_spec.SetField(s3backend.FieldKeyPrefix, field.TypeString, value)
		_node.KeyPrefix = value
	}
	if value, ok := _c.mutation.MountPath(); ok {
		_spec.SetField(s3backend.FieldMountPath, field.TypeString, value)
		_node.MountPath = value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(s3backend.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = value
	}
	if value, ok := _c.mutation.IsReadonly(); ok {
		_spec.SetField(s3backend.FieldIsReadonly, field.TypeBool, value)
		_node.IsReadonly = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(s3backend.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(s3backend.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   s3backend.UsersTable,
			Columns: s3backend.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// S3BackendCreateBulk is the builder for creating many S3Backend entities in bulk.
type S3BackendCreateBulk struct {
	config
	err      error
	builders []*S3BackendCreate
}

// Save creates the S3Backend entities in the database.
func (_c *S3BackendCreateBulk) Save(ctx context.Context) ([]*S3Backend, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*S3Backend, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*S3BackendMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *S3BackendCreateBulk) SaveX(ctx context.Context) []*S3Backend {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *S3BackendCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *S3BackendCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
