// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// S3Backend is the predicate function for s3backend builders.
type S3Backend func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
